import type { QuizQuestion } from '@/types';

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'health-focus',
    question: "What matters most to you right now?",
    subtitle: "Pick up to 3 — we'll use these to find tests tailored to your goals.",
    type: 'multi-select',
    maxSelections: 3,
    options: [
      { id: 'energy', label: 'More Energy', icon: '⚡', goalWeights: { 'increase-energy': 3 } },
      { id: 'hormones', label: 'Hormone Balance', icon: '🧬', goalWeights: { 'evaluate-hormones': 3 } },
      { id: 'gut', label: 'Gut & Digestion', icon: '🫁', goalWeights: { 'improve-gut-health': 3 } },
      { id: 'performance', label: 'Athletic Performance', icon: '🏋️', goalWeights: { 'optimize-performance': 3 } },
      { id: 'weight', label: 'Weight Management', icon: '⚖️', goalWeights: { 'support-weight-management': 3 } },
      { id: 'immune', label: 'Immune Support', icon: '🛡️', goalWeights: { 'boost-immune-health': 3 } },
      { id: 'sleep', label: 'Better Sleep', icon: '😴', goalWeights: { 'improve-sleep': 3 } },
      { id: 'heart', label: 'Heart Health', icon: '❤️', goalWeights: { 'assess-heart-health': 3 } },
      { id: 'mental', label: 'Mental Clarity', icon: '🧠', goalWeights: { 'enhance-mental-clarity': 3 } },
      { id: 'longevity', label: 'Anti-Aging & Longevity', icon: '🕰️', goalWeights: { 'anti-aging-longevity': 3 } },
    ],
  },
  {
    id: 'symptoms',
    question: "What\u2019s been bothering you most?",
    subtitle: "Select all that sound familiar (up to 4). Your symptoms are real \u2014 let\u2019s find out why.",
    type: 'multi-select',
    maxSelections: 4,
    options: [
      { id: 'fatigue', label: 'Tired all the time, even after sleeping', goalWeights: { 'increase-energy': 2, 'improve-sleep': 1 } },
      { id: 'brain-fog', label: "Brain fog that won't go away", goalWeights: { 'enhance-mental-clarity': 2, 'increase-energy': 1 } },
      { id: 'digestive', label: 'Bloating, gas, or heartburn', goalWeights: { 'improve-gut-health': 2 } },
      { id: 'weight-gain', label: 'Struggling with weight despite trying', goalWeights: { 'support-weight-management': 2 } },
      { id: 'mood', label: 'Mood swings or feeling on edge', goalWeights: { 'evaluate-hormones': 2, 'enhance-mental-clarity': 1 } },
      { id: 'low-libido', label: 'Low libido or drive', goalWeights: { 'evaluate-hormones': 2 } },
      { id: 'joint-pain', label: 'Joint pain or slow recovery', goalWeights: { 'optimize-performance': 2, 'boost-immune-health': 1 } },
      { id: 'illness', label: 'Getting sick more often than usual', goalWeights: { 'boost-immune-health': 2 } },
      { id: 'poor-sleep', label: "Can't sleep through the night", goalWeights: { 'improve-sleep': 2 } },
      { id: 'none', label: 'None of the above', goalWeights: {} },
    ],
  },
  {
    id: 'energy-level',
    question: 'How would you describe your energy throughout the day?',
    type: 'single-select',
    options: [
      { id: 'crash', label: 'I crash by mid-afternoon, even when I eat well', goalWeights: { 'increase-energy': 2, 'support-weight-management': 1 } },
      { id: 'low-all-day', label: 'Consistently low — it feels like running on empty', goalWeights: { 'increase-energy': 2, 'evaluate-hormones': 1 } },
      { id: 'could-be-better', label: 'Not bad, but I know I could feel better', goalWeights: { 'increase-energy': 1 } },
      { id: 'great', label: 'My energy is solid throughout the day', goalWeights: {} },
    ],
  },
  {
    id: 'sleep-quality',
    question: 'What does sleep look like for you?',
    type: 'single-select',
    options: [
      { id: 'cant-fall-asleep', label: "My mind won't shut off \u2014 I can't fall asleep", goalWeights: { 'improve-sleep': 2, 'evaluate-hormones': 1 } },
      { id: 'wake-frequently', label: 'I wake up multiple times during the night', goalWeights: { 'improve-sleep': 2, 'evaluate-hormones': 1 } },
      { id: 'wake-tired', label: 'I sleep enough hours but still wake up exhausted', goalWeights: { 'improve-sleep': 2, 'increase-energy': 1 } },
      { id: 'sleep-well', label: 'I sleep well and feel rested', goalWeights: {} },
    ],
  },
  {
    id: 'hormonal-concerns',
    question: 'Have you noticed any of these changes in your body?',
    subtitle: "Select all that apply \u2014 these can point us to what\u2019s really going on.",
    type: 'multi-select',
    options: [
      { id: 'low-drive', label: 'Lower sex drive than usual', goalWeights: { 'evaluate-hormones': 2 } },
      { id: 'hair-loss', label: 'Hair thinning or loss', goalWeights: { 'evaluate-hormones': 2, 'anti-aging-longevity': 1 } },
      { id: 'unexplained-weight', label: 'Weight changes without changing habits', goalWeights: { 'evaluate-hormones': 2, 'support-weight-management': 1 } },
      { id: 'hot-flashes', label: 'Hot flashes or night sweats', goalWeights: { 'evaluate-hormones': 2 } },
      { id: 'not-sure', label: "Something feels off, but I'm not sure what", goalWeights: { 'evaluate-hormones': 1 } },
      { id: 'no-concerns', label: 'None of these apply', goalWeights: {} },
    ],
  },
  {
    id: 'digestion',
    question: 'How does your gut feel on a typical day?',
    type: 'single-select',
    options: [
      { id: 'bloating', label: 'Bloating or discomfort after eating', goalWeights: { 'improve-gut-health': 2 } },
      { id: 'sensitivities', label: "Certain foods bother me, but I can't figure out which", goalWeights: { 'improve-gut-health': 2 } },
      { id: 'irregular', label: 'Things are unpredictable day to day', goalWeights: { 'improve-gut-health': 2 } },
      { id: 'fine', label: 'My digestion feels good', goalWeights: {} },
    ],
  },
  {
    id: 'activity-level',
    question: 'How physically active are you?',
    type: 'single-select',
    options: [
      { id: 'competitive', label: 'Competitive athlete or intense training', goalWeights: { 'optimize-performance': 2, 'anti-aging-longevity': 1 } },
      { id: 'regular', label: 'Regular exercise (3-5x/week)', goalWeights: { 'optimize-performance': 1 } },
      { id: 'light', label: 'Light activity (walking, yoga)', goalWeights: { 'support-weight-management': 1 } },
      { id: 'sedentary', label: 'Mostly sedentary', goalWeights: { 'support-weight-management': 1, 'assess-heart-health': 1 } },
    ],
  },
  {
    id: 'genetics-interest',
    question: 'Interested in what your DNA can tell you?',
    subtitle: 'Genetic testing reveals what your body uniquely needs for nutrition, detox, and long-term health.',
    type: 'single-select',
    options: [
      { id: 'nutrition', label: 'Yes — for nutrition & diet guidance', testBoosts: { 'precision-genetics': 3 } },
      { id: 'methylation', label: 'Yes — for methylation & detox pathways', testBoosts: { 'methylation-genetics': 3 } },
      { id: 'both', label: 'Yes — both!', testBoosts: { 'precision-genetics': 3, 'methylation-genetics': 3 } },
      { id: 'not-interested', label: 'Not interested right now', goalWeights: {} },
    ],
  },
  {
    id: 'age-range',
    question: "What's your age range?",
    type: 'single-select',
    options: [
      { id: '18-29', label: '18-29', goalWeights: { 'optimize-performance': 1 } },
      { id: '30-39', label: '30-39', goalWeights: { 'evaluate-hormones': 1, 'optimize-performance': 1 } },
      { id: '40-49', label: '40-49', goalWeights: { 'evaluate-hormones': 1, 'anti-aging-longevity': 1, 'assess-heart-health': 1 } },
      { id: '50-plus', label: '50+', goalWeights: { 'anti-aging-longevity': 2, 'assess-heart-health': 1, 'evaluate-hormones': 1 } },
    ],
  },
  {
    id: 'family-history',
    question: 'Is there a history of any of these in your family?',
    subtitle: 'This helps us focus on prevention — catching it before it becomes a problem.',
    type: 'multi-select',
    options: [
      { id: 'heart-disease', label: 'Heart disease', goalWeights: { 'assess-heart-health': 2 } },
      { id: 'diabetes', label: 'Diabetes', goalWeights: { 'support-weight-management': 1, 'assess-heart-health': 1 } },
      { id: 'autoimmune', label: 'Autoimmune conditions', goalWeights: { 'boost-immune-health': 2, 'improve-gut-health': 1 } },
      { id: 'cancer', label: 'Cancer', goalWeights: { 'anti-aging-longevity': 1 } },
      { id: 'none', label: 'None / not sure', goalWeights: {} },
    ],
  },
  {
    id: 'collection-preference',
    question: 'How would you prefer to collect your samples?',
    type: 'single-select',
    options: [
      { id: 'in-person', label: 'I want the most comprehensive results', description: 'In-person blood draw works for me', preferenceFlag: 'in-person' },
      { id: 'at-home', label: 'Convenience matters most', description: 'I prefer collecting from the comfort of home', preferenceFlag: 'at-home' },
      { id: 'any', label: 'Whatever gets me the best answers', preferenceFlag: 'any' },
    ],
  },
  {
    id: 'budget',
    question: 'What investment feels right for getting answers about your health?',
    type: 'single-select',
    options: [
      { id: 'low', label: 'Under $300', preferenceFlag: 'low' },
      { id: 'mid', label: '$300 – $700', preferenceFlag: 'mid' },
      { id: 'high', label: '$700 – $1,000', preferenceFlag: 'high' },
      { id: 'unlimited', label: 'I want the best regardless of cost', preferenceFlag: 'unlimited' },
    ],
  },
];
