import type { QuizQuestion } from '@/types';

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'health-focus',
    question: "What's your primary health focus right now?",
    subtitle: 'Select up to 3 that matter most to you.',
    type: 'multi-select',
    maxSelections: 3,
    options: [
      { id: 'energy', label: 'More Energy', icon: '⚡', goalWeights: { 'increase-energy': 3 } },
      { id: 'hormones', label: 'Hormone Balance', icon: '🧬', goalWeights: { 'evaluate-hormones': 3 } },
      { id: 'gut', label: 'Gut & Digestion', icon: '🫁', goalWeights: { 'improve-gut-health': 3 } },
      { id: 'performance', label: 'Athletic Performance', icon: '🏋️', goalWeights: { 'optimize-performance': 3 } },
      { id: 'weight', label: 'Weight Management', icon: '⚖️', goalWeights: { 'support-weight-management': 3 } },
      { id: 'immune', label: 'Immune Support', icon: '🛡️', goalWeights: { 'boost-immune-health': 3 } },
      { id: 'sleep', label: 'Better Sleep', icon: '😴', goalWeights: { 'improve-sleep': 3 } },
      { id: 'heart', label: 'Heart Health', icon: '❤️', goalWeights: { 'assess-heart-health': 3 } },
      { id: 'mental', label: 'Mental Clarity', icon: '🧠', goalWeights: { 'enhance-mental-clarity': 3 } },
      { id: 'longevity', label: 'Anti-Aging & Longevity', icon: '🕰️', goalWeights: { 'anti-aging-longevity': 3 } },
    ],
  },
  {
    id: 'symptoms',
    question: 'Which symptoms bother you most?',
    subtitle: 'Select all that apply (up to 4).',
    type: 'multi-select',
    maxSelections: 4,
    options: [
      { id: 'fatigue', label: 'Fatigue / low energy', goalWeights: { 'increase-energy': 2, 'improve-sleep': 1 } },
      { id: 'brain-fog', label: 'Brain fog / poor concentration', goalWeights: { 'enhance-mental-clarity': 2, 'increase-energy': 1 } },
      { id: 'digestive', label: 'Digestive issues (bloating, gas, reflux)', goalWeights: { 'improve-gut-health': 2 } },
      { id: 'weight-gain', label: 'Weight gain or difficulty losing weight', goalWeights: { 'support-weight-management': 2 } },
      { id: 'mood', label: 'Mood swings or irritability', goalWeights: { 'evaluate-hormones': 2, 'enhance-mental-clarity': 1 } },
      { id: 'low-libido', label: 'Low libido', goalWeights: { 'evaluate-hormones': 2 } },
      { id: 'joint-pain', label: 'Joint pain or slow recovery', goalWeights: { 'optimize-performance': 2, 'boost-immune-health': 1 } },
      { id: 'illness', label: 'Frequent illness', goalWeights: { 'boost-immune-health': 2 } },
      { id: 'poor-sleep', label: 'Poor sleep / insomnia', goalWeights: { 'improve-sleep': 2 } },
      { id: 'none', label: 'None of the above', goalWeights: {} },
    ],
  },
  {
    id: 'energy-level',
    question: 'How would you describe your energy levels?',
    type: 'single-select',
    options: [
      { id: 'crash', label: 'I crash by mid-afternoon', goalWeights: { 'increase-energy': 2, 'support-weight-management': 1 } },
      { id: 'low-all-day', label: 'Consistently low all day', goalWeights: { 'increase-energy': 2, 'evaluate-hormones': 1 } },
      { id: 'could-be-better', label: 'Good but could be better', goalWeights: { 'increase-energy': 1 } },
      { id: 'great', label: 'Generally great', goalWeights: {} },
    ],
  },
  {
    id: 'sleep-quality',
    question: 'How is your sleep?',
    type: 'single-select',
    options: [
      { id: 'cant-fall-asleep', label: 'I struggle to fall asleep', goalWeights: { 'improve-sleep': 2, 'evaluate-hormones': 1 } },
      { id: 'wake-frequently', label: 'I wake up frequently', goalWeights: { 'improve-sleep': 2, 'evaluate-hormones': 1 } },
      { id: 'wake-tired', label: 'I sleep but wake up tired', goalWeights: { 'improve-sleep': 2, 'increase-energy': 1 } },
      { id: 'sleep-well', label: 'I sleep well', goalWeights: {} },
    ],
  },
  {
    id: 'hormonal-concerns',
    question: 'Have you experienced hormonal changes or concerns?',
    subtitle: 'Select all that apply.',
    type: 'multi-select',
    options: [
      { id: 'low-drive', label: 'Low sex drive', goalWeights: { 'evaluate-hormones': 2 } },
      { id: 'hair-loss', label: 'Hair thinning or loss', goalWeights: { 'evaluate-hormones': 2, 'anti-aging-longevity': 1 } },
      { id: 'unexplained-weight', label: 'Weight changes without lifestyle changes', goalWeights: { 'evaluate-hormones': 2, 'support-weight-management': 1 } },
      { id: 'hot-flashes', label: 'Hot flashes or night sweats', goalWeights: { 'evaluate-hormones': 2 } },
      { id: 'not-sure', label: "I'm not sure", goalWeights: { 'evaluate-hormones': 1 } },
      { id: 'no-concerns', label: 'No concerns', goalWeights: {} },
    ],
  },
  {
    id: 'digestion',
    question: 'How is your digestion?',
    type: 'single-select',
    options: [
      { id: 'bloating', label: 'Frequent bloating or discomfort', goalWeights: { 'improve-gut-health': 2 } },
      { id: 'sensitivities', label: "Food sensitivities I can't pinpoint", goalWeights: { 'improve-gut-health': 2 } },
      { id: 'irregular', label: 'Irregular bowel habits', goalWeights: { 'improve-gut-health': 2 } },
      { id: 'fine', label: 'Digestion is fine', goalWeights: {} },
    ],
  },
  {
    id: 'activity-level',
    question: 'How physically active are you?',
    type: 'single-select',
    options: [
      { id: 'competitive', label: 'Competitive athlete or intense training', goalWeights: { 'optimize-performance': 2, 'anti-aging-longevity': 1 } },
      { id: 'regular', label: 'Regular exercise (3-5x/week)', goalWeights: { 'optimize-performance': 1 } },
      { id: 'light', label: 'Light activity (walking, yoga)', goalWeights: { 'support-weight-management': 1 } },
      { id: 'sedentary', label: 'Mostly sedentary', goalWeights: { 'support-weight-management': 1, 'assess-heart-health': 1 } },
    ],
  },
  {
    id: 'genetics-interest',
    question: 'Are you interested in understanding your genetics?',
    subtitle: 'Genetic tests reveal how your DNA affects nutrition, detox, and health.',
    type: 'single-select',
    options: [
      { id: 'nutrition', label: 'Yes — for nutrition & diet guidance', testBoosts: { 'precision-genetics': 3 } },
      { id: 'methylation', label: 'Yes — for methylation & detox pathways', testBoosts: { 'methylation-genetics': 3 } },
      { id: 'both', label: 'Yes — both!', testBoosts: { 'precision-genetics': 3, 'methylation-genetics': 3 } },
      { id: 'not-interested', label: 'Not interested right now', goalWeights: {} },
    ],
  },
  {
    id: 'age-range',
    question: "What's your age range?",
    type: 'single-select',
    options: [
      { id: '18-29', label: '18-29', goalWeights: { 'optimize-performance': 1 } },
      { id: '30-39', label: '30-39', goalWeights: { 'evaluate-hormones': 1, 'optimize-performance': 1 } },
      { id: '40-49', label: '40-49', goalWeights: { 'evaluate-hormones': 1, 'anti-aging-longevity': 1, 'assess-heart-health': 1 } },
      { id: '50-plus', label: '50+', goalWeights: { 'anti-aging-longevity': 2, 'assess-heart-health': 1, 'evaluate-hormones': 1 } },
    ],
  },
  {
    id: 'family-history',
    question: 'Do you have a family history of any of the following?',
    subtitle: 'Select all that apply.',
    type: 'multi-select',
    options: [
      { id: 'heart-disease', label: 'Heart disease', goalWeights: { 'assess-heart-health': 2 } },
      { id: 'diabetes', label: 'Diabetes', goalWeights: { 'support-weight-management': 1, 'assess-heart-health': 1 } },
      { id: 'autoimmune', label: 'Autoimmune conditions', goalWeights: { 'boost-immune-health': 2, 'improve-gut-health': 1 } },
      { id: 'cancer', label: 'Cancer', goalWeights: { 'anti-aging-longevity': 1 } },
      { id: 'none', label: 'None / not sure', goalWeights: {} },
    ],
  },
  {
    id: 'collection-preference',
    question: "What's your preference for sample collection?",
    type: 'single-select',
    options: [
      { id: 'in-person', label: 'I want the most comprehensive test', description: 'In-person blood draw is fine', preferenceFlag: 'in-person' },
      { id: 'at-home', label: 'At-home convenience is important', description: 'Prefer collecting samples from home', preferenceFlag: 'at-home' },
      { id: 'any', label: 'A mix of both works', preferenceFlag: 'any' },
    ],
  },
  {
    id: 'budget',
    question: "What's your budget range for testing?",
    type: 'single-select',
    options: [
      { id: 'low', label: 'Under $150', preferenceFlag: 'low' },
      { id: 'mid', label: '$150 – $300', preferenceFlag: 'mid' },
      { id: 'high', label: '$300 – $600', preferenceFlag: 'high' },
      { id: 'unlimited', label: 'I want the best regardless of cost', preferenceFlag: 'unlimited' },
    ],
  },
];
